### ISSUE TITLE
Training Data Generator Code

### ISSUE THREAD

**Issue by mustfkeskin** [Lettria/Char2Vec#1]
"This data has been generated using a 600K words dictionnary and a custom typing-error generator."

Do you have data generator from given corpus?

**Comment by maxencealluin** [comment]
I can't share the code but it is easy to write your own basic generator by following the blog post from Peter Norvig (https://norvig.com/spell-correct.html).
This part in particular gives a list of all possible misspelling for a given word.

`def edits1(word):
    "All edits that are one edit away from `word`."
    letters    = 'abcdefghijklmnopqrstuvwxyz'
    splits     = [(word[:i], word[i:])    for i in range(len(word) + 1)]
    deletes    = [L + R[1:]               for L, R in splits if R]
    transposes = [L + R[1] + R[0] + R[2:] for L, R in splits if len(R)>1]
    replaces   = [L + c + R[1:]           for L, R in splits if R for c in letters]
    inserts    = [L + c + R               for L, R in splits for c in letters]
    return set(deletes + transposes + replaces + inserts)

def edits2(word): 
    "All edits that are two edits away from `word`."
    return (e2 for e1 in edits1(word) for e2 in edits1(e1))`

Our generator works on this basis but is adapted to favor misspellings according to an azerty keyboard.
