### ISSUE TITLE
Something wrong with training_data.json content

### ISSUE THREAD

**Issue by AntoninaGerasiova** [Lettria/Char2Vec#3]
Hello. When I load data from training_data.json with code 
`X_train, y_train = r[0], r[1]`
X_train === y_train (two copies of the same data), which doesn't make any sense and model also complains. Shouldn't y_train be some sort of target, for example 0 for random pair an 1 for word and it's misspelled version (or vice versa)?

**Comment by maxencealluin** [comment]
You are absolutely right, something went wrong and the targets got replaced, I fixed it (better late than never I guess).
